version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: api
    env_file: .env
    ports:
      - "8081:8081"
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1G

  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ports:
      - "9201:9200"
    deploy:
      resources:
        limits:
          memory: 1G

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
