version: '3.8'

services:
  nextjs:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/app #live reloead

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
