version: "3"

services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   image: api
  #   env_file: .env
  #   ports:
  #     - "8081:8081"
  #     - "8080:8080"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G

  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - "9201:9200"
    deploy:
      resources:
        limits:
          memory: 0.5G

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.5.2
  #   ports:
  #     - 5601:5601
